### ISSUE TITLE
Annoying warning

### ISSUE THREAD

**Issue by maasha** [colszowka/simplecov-html#37]
I am kind of tired of seeing this every time I run my test suite :o) - I hope it can be fixed.

/usr/local/lib/ruby/gems/2.2.0/gems/simplecov-html-0.8.0/lib/simplecov-html.rb:58: warning: possibly useless use of a variable in void context

**Comment by maasha** [comment]
The offending line even says "FIXME" :o)

**Comment by xaviershay** [comment]
This was fixed in 43141a04. It will be in the next release. @colszowka we should probably patch release, given doesn't look like this repo gets much activity.

**Comment by bf4** [comment]
ping @colszowka `gem owner simplecov` has me and @xaviershay, but `gem owner simplecov-html` has you alone :(

**Comment by colszowka** [comment]
@bf4 Thanks for the heads up, you, @sferik and @xaviershay should now all be also owners of the `simplecov-html` gem. I'll verify #36 works fine and will ship 0.9.0 today.

**Comment by colszowka** [comment]
Arghs, so it turns out we have a ~> 0.8.0 version dependency in the simplecov gemspec, which prevents me from shipping this as 0.9.0 for SimpleCov 0.9.1.

@bf4 @xaviershay What do you think, should we rather ship this as 0.8.1 to avoid having to bump simplecov as well, or rather ship SimpleCov 0.9.2 with an updated gem dependency of ~> 0.9.0 and then ship this as 0.9.0 to keep version parity?

**Comment by bf4** [comment]
Change it to `gem.add_runtime_dependency 'simplecov-html', '~> 0.8'` and it works for everyone, no?

**Comment by colszowka** [comment]
@bf4 People will still need to update simplecov to 0.9.2 then, and would be allowed to use the 0.8 tree of simplecov-html, so some might miss the bugfixes. I'll make it ~> 0.9.0 so we have parity between simplecov version numbers and simplecov-html

**Comment by xaviershay** [comment]
seems good
