### ISSUE TITLE
Can't be used without rubygems loaded

### ISSUE THREAD

**Issue by myronmarston** [colszowka/simplecov-html#38]
While rubygems is loaded by default on 1.9+, there are situations where it is desirable not to load it, and you can use ruby's `--disable=gem` flag to disable it.  We're trying to update RSpec's travis builds to run with rubygems disable, and are running into unitinialized constant by your use of `Gem::Version`:

https://github.com/colszowka/simplecov-html/blob/65238a35cda44956e87dd520086095cbf1f2370d/lib/simplecov-html.rb#L8

Can this version constraint be moved into the gemspec?  That would allow bundler to ensure this and simplecov are compatible, where as it can't due that when it's purely a runtime check like you have now.

**Comment by colszowka** [comment]
Hey Myron, the trouble with the gemspec is that you get a circular dependency. I ran into that when releasing 0.1.0 back in the day and hence went with the Gem::Version approach since I was assuming that would always be present.

Maybe now a circular dependency would work and maybe I did something wrong with the early releases *shrug*

Technically it might be a point that the dependency from the HTML gem side is pointless since theoretically it does not require simplecov, so maybe it should be dropped altogether.

**Comment by myronmarston** [comment]
Ah, I had forgotten that simplecov declares a dependency on this gem.  That surprises me -- I thought the point of having simplecov-html as a separate gem rather than having the functionality built-in to the simplecov gem was to make `simoplecov-html` an optional extra, but as long as it is declared as a required dependency of `simplecov` I don't understand the benefit of it being a separate gem/repo.

Have you considered either rolling `simplecov-html` into `simplecov` (if you want to keep it as a required dependency -- you could still keep it as something that's not loaded by default and that users must manually require to use if you want) or removing the dependency declaration from the `simplecov` gem and instead making `simplecov-html` depend upon `simplecov` in its gemspec?

**Comment by bf4** [comment]
I think string comparison would be fine as long as we don't go to `0.10.0`

**Comment by bf4** [comment]
I made a PR with a pretty simple solution. https://github.com/colszowka/simplecov-html/pull/39  I'm not sure if it needs to be more robust. I'm open to adding a test, and moving the logic into 'simplecov/version'
